--MOSTRAR TODOS LOS REGISTROS
SELECT * FROM PRODUCTO;
SELECT * FROM PROVEEDOR;
SELECT * FROM TELEFONO;
SELECT * FROM CLIENTE;
SELECT * FROM EMAIL;
SELECT * FROM VENTA;
SELECT * FROM BRINDA;
SELECT * FROM INCLUYE;

--PARA LOS PRODUCTOS SI NO QUEREMOS QUE EL USUARIO VEA LA FECHAC Y PRECIOC , REMPLAZAR POR EL *
-- (ARTICULO,MARCA, DESCRIPCION,PRECIOV,STOCK)

--MOSTRAR TODOS LOS PRODUCTOS QUE TENGAN MENOS DE 3 EN STOCK
SELECT * FROM PRODUCTO
WHERE STOCK < 3;

--MOSTRAR LOS PRODUCTOS POR ORDEN DE PRECIO (M-m)
SELECT * FROM PRODUCTO
ORDER BY PRECIOV DESC;

--MOSTRAR LOS PRODUCTOS POR ORDEN DE PRECIO (m-M)
SELECT * FROM PRODUCTO
ORDER BY PRECIOV;

--BUSQEUDA POR ARTICULO 
SELECT (ARTICULO,MARCA, DESCRIPCION,PRECIOV,STOCK) FROM PRODUCTO WHERE ARTICULO = 'GOMA';

--MOSTAR TOTAL DE UNA VENTA
SELECT TOTALV FROM VENTA WHERE NOVENTA = 'VENT-1';

--MOSTAR VENTAS QUE PERTENESCAN A ESA FECHA
SELECT * FROM VENTA 
WHERE FECHAV = '14-06-2021';

--MOSTRAR VENTAS QUE PERTENESCAN A ESAS DOS FECHAS
SELECT * FROM VENTA 
WHERE FECHAV IN('01-06-2021','14-06-2021');

--MOSTRAR GANANCIAS POR DIA
SELECT FECHAV, SUM(TOTALV) AS "TOTAL POR DIA"
FROM VENTA 
GROUP BY FECHAV
ORDER BY FECHAV;

--MOSTAR GANACIAS EN UN PERIODO DE DIAS
SELECT FECHAV, SUM(TOTALV) 
FROM VENTA 
WHERE FECHAV BETWEEN '01-06-2021' AND '14-06-2021'
GROUP BY FECHAV
ORDER BY FECHAV;

--MOSTAR EL TOTAL DE TODO EL TIEMPO, SE BORRA AL INICIAR
--SE INCERTA LA CONSULTA DE VENTAS EN EL PERIODO DE FECHAS Y SE SUMA DE LA TABLA AUXILIAR
DELETE FROM TTOTALV;

INSERT INTO TTOTALV (DIAV,TOTALS) 
SELECT FECHAV, SUM(TOTALV) 
    FROM VENTA 
    WHERE FECHAV BETWEEN '02-06-2021' AND '10-06-2021'
    GROUP BY FECHAV
    ORDER BY FECHAV;

SELECT SUM(TOTALS) AS TOTAL FROM TTOTALV;

--VER EL SIGUIENTE NUMERO DE LA SECUENCIA DE VENTA
SELECT nextval('SQ_VENTA');
-- mostar el valor siguiente de la secuencia, pero sin cambiarlo
SELECT last_value +1 from SQ_VENTA;


--MOSTRAR DATOs DE VENTA CON JOIN
SELECT I.CODIGOBARRAS, P.ARTICULO, P.MARCA, P.PRECIOV, I.CANTIDADPROD, I.TOTALP
FROM PRODUCTO P INNER JOIN INCLUYE I
ON P.CODIGOBARRAS = I.CODIGOBARRAS
WHERE NOVENTA = 'VENT-1';

--MOSTRAR TOTAL DE FECHAS SIN TEM TABLE
SELECT SUM(SELECT FECHAV, SUM(TOTALV) 
    FROM VENTA 
    WHERE FECHAV BETWEEN '02-06-2021' AND '10-06-2021'
    GROUP BY FECHAV
    ORDER BY FECHAV) FROM VENTA;