--CREACION DE TABLAS:
CREATE TABLE PRODUCTO(
    CODIGOBARRAS BIGINT,
    ARTICULO VARCHAR(50),
    FECHAC DATE,
    PRECIOC FLOAT CHECK (PRECIOC >0),
    MARCA VARCHAR(20),
    DESCRIPCION VARCHAR(100),
    PRECIOV FLOAT CHECK (PRECIOV >0),
    STOCK INTEGER CHECK (STOCK >=0),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGOBARRAS)
);

CREATE TABLE PROVEEDOR(
    RAZONSOCIAL INTEGER,
    PNOMBREP VARCHAR(30),
    APELLIDOPP VARCHAR(40),
    APELLIDOMP VARCHAR(40),
    CALLEP VARCHAR(50),
    COLONIAP VARCHAR(50),
    CPP INTEGER,
    NUMEROCALLEP INTEGER,
    ESTADOP VARCHAR(50),
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (RAZONSOCIAL)
);

CREATE TABLE TELEFONO(
    TELL BIGINT,
    RAZONSOCIAL INTEGER,
    CONSTRAINT PK_TELEFONO PRIMARY KEY (TELL)
);

CREATE TABLE CLIENTE(
    RFC VARCHAR(13),
    PNOMBREC VARCHAR(30),
    APELLIDOPC VARCHAR(40),
    APELLIDOMC VARCHAR(40),
    CALLEC VARCHAR(50),
    COLONIAC VARCHAR(50),
    CPC INTEGER,
    NUMEROCALLEC INTEGER,
    ESTADOC VARCHAR(50),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (RFC)
);

CREATE TABLE EMAIL(
    CORREO VARCHAR(150),
    RFC VARCHAR(13),
    CONSTRAINT PK_EMAIL PRIMARY KEY (CORREO)
);

        
CREATE TABLE VENTA(
    NOVENTA VARCHAR(8),
    FECHAV DATE,
    TOTALV FLOAT,
    RFC VARCHAR(13),
    CONSTRAINT PK_VENTA PRIMARY KEY (NOVENTA)
);

--PK COMPUESTAS
CREATE TABLE BRINDA(
    RAZONSOCIAL INTEGER,
    CODIGOBARRAS INTEGER,
    CANTIDADDADA INTEGER,
    PRIMARY KEY (RAZONSOCIAL,CODIGOBARRAS)
);

CREATE TABLE INCLUYE(
    CODIGOBARRAS INTEGER,
    NOVENTA VARCHAR(8),
    CANTIDADPROD INTEGER,
    TOTALP FLOAT,
    PRIMARY KEY (CODIGOBARRAS,NOVENTA)
);

--CREACION DE FK:
ALTER TABLE TELEFONO ADD CONSTRAINT FK_PROVEEDOR_TELEFONO FOREIGN KEY (RAZONSOCIAL)
REFERENCES PROVEEDOR (RAZONSOCIAL);

ALTER TABLE EMAIL ADD CONSTRAINT FK_CLIENTE_EMAIL FOREIGN KEY (RFC)
REFERENCES CLIENTE (RFC);

ALTER TABLE VENTA ADD CONSTRAINT FK_CLIENTE_VENTA FOREIGN KEY (RFC)
REFERENCES CLIENTE (RFC);

ALTER TABLE BRINDA ADD CONSTRAINT FK_PROVEEDOR_BRINDA FOREIGN KEY (RAZONSOCIAL)
REFERENCES PROVEEDOR (RAZONSOCIAL);

ALTER TABLE BRINDA ADD CONSTRAINT FK_PRODUCTO_BRINDA FOREIGN KEY (CODIGOBARRAS)
REFERENCES PRODUCTO (CODIGOBARRAS);

ALTER TABLE INCLUYE ADD CONSTRAINT FK_PRODUCTO_INCLUYE FOREIGN KEY (CODIGOBARRAS)
REFERENCES PRODUCTO (CODIGOBARRAS);

ALTER TABLE INCLUYE ADD CONSTRAINT FK_VENTA_INCLUYE FOREIGN KEY (NOVENTA)
REFERENCES VENTA (NOVENTA);

--Tabla auxiliar para el calculo de ganancias
CREATE TABLE TTOTALV(
    DIAV DATE PRIMARY KEY,
    TOTALS FLOAT
);

DROP TABLE TTOTALV;

--CREACION DEL INDICE
CREATE  INDEX INDEX_PRODUCTO ON
PRODUCTO (ARTICULO);

--MOSTRAR TODOS LOS REGISTROS
SELECT * FROM PRODUCTO;
SELECT * FROM PROVEEDOR;
SELECT * FROM TELEFONO;
SELECT * FROM CLIENTE;
SELECT * FROM EMAIL;
SELECT * FROM VENTA;
SELECT * FROM BRINDA;
SELECT * FROM INCLUYE;

--Eliminacion definitiva de las tablas
DROP TABLE PRODUCTO CASCADE;
DROP TABLE PROVEEDOR CASCADE;
DROP TABLE TELEFONO CASCADE;
DROP TABLE CLIENTE CASCADE;
DROP TABLE EMAIL CASCADE;
DROP TABLE VENTA CASCADE;
DROP TABLE BRINDA CASCADE;
DROP TABLE INCLUYE CASCADE;

