-- Tabla: PROVEEDOR
CREATE TABLE PROVEEDOR (
    RS VARCHAR(150) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellidoP VARCHAR(100) NOT NULL,
    apellidoM VARCHAR(100) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    numero INTEGER NOT NULL,
    codigoPostal BIGINT NOT NULL,
    CONSTRAINT proveedor_pk PRIMARY KEY(RS)
);


-- Tabla: TELEFONO
CREATE TABLE TELEFONO (
    telefono BIGINT NOT NULL,
    RS VARCHAR(150) NOT NULL,
	CONSTRAINT RS_telefono_fk FOREIGN KEY (RS) REFERENCES PROVEEDOR (RS) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT telefono_pk PRIMARY KEY (telefono, RS) 
);

-- Tabla: PRODUCTO
CREATE TABLE PRODUCTO (
    codBarras VARCHAR(20) NOT NULL,
    precio NUMERIC(10,2) NOT NULL,
    fechaCompra DATE NOT NULL,
    stock INT NOT NULL,
    foto BYTEA, 
    RS VARCHAR(150) NOT NULL,
	CONSTRAINT RS_producto_fk FOREIGN KEY (RS) REFERENCES PROVEEDOR (RS) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT codBarras_pk PRIMARY KEY (codBarras) 
);

-- Tabla: EMPLEADO
CREATE TABLE EMPLEADO (
    clave VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellidoP VARCHAR(100) NOT NULL,
    apellidoM VARCHAR(100) NOT NULL,
    fechaNac DATE NOT NULL,
	fechaIng DATE NOT NULL,
    calle VARCHAR(100) NOT NULL,
	estado VARCHAR(100) NOT NULL,
    colonia VARCHAR(100) NOT NULL,
    numero INT NOT NULL,
    codigoPostal BIGINT NOT NULL,
	CONSTRAINT clave_pk PRIMARY KEY (clave)
);

-- Tabla: CLIENTE
CREATE TABLE CLIENTE (
    rfc VARCHAR(13) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellidoP VARCHAR(100) NOT NULL,
    apellidoM VARCHAR(100) NOT NULL,
	colonia VARCHAR(100) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    estado VARCHAR(100) NOT NULL,
    numero INTEGER NOT NULL,
    codigoPostal BIGINT NOT NULL,
	CONSTRAINT cliente_pk PRIMARY KEY (rfc)
);

-- Tabla: EMAIL
CREATE TABLE EMAIL (
    email VARCHAR(50) NOT NULL,
    rfc VARCHAR(13) NOT NULL,
	CONSTRAINT rfc_email_fk FOREIGN KEY (rfc) REFERENCES CLIENTE (rfc) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT email_pk PRIMARY KEY (rfc, email) 
);

-- Tabla: VENTA
CREATE TABLE VENTA (
    numero VARCHAR(9) NOT NULL,
    fecha DATE NOT NULL,
    clave VARCHAR(50) NOT NULL,
    rfc VARCHAR(13) NOT NULL,
    total NUMERIC(10,2),
    CONSTRAINT venta_pk PRIMARY KEY (numero),
	CONSTRAINT rfc_venta_fk FOREIGN KEY (rfc) REFERENCES CLIENTE (rfc) ON DELETE CASCADE ON UPDATE RESTRICT,
	CONSTRAINT clave_venta_fk FOREIGN KEY (clave) REFERENCES EMPLEADO (clave) ON DELETE CASCADE ON UPDATE RESTRICT
);

-- Tabla: CONTIENE
CREATE TABLE CONTIENE_PRODUCTO_VENTA (
    codBarras VARCHAR(20) NOT NULL,
    numero VARCHAR(9) NOT NULL,
    precioArticulo NUMERIC(10,2),
    cantArticulo INTEGER NOT NULL,
	CONSTRAINT codBarras_contiene_fk FOREIGN KEY (codBarras) REFERENCES PRODUCTO (codBarras) ON DELETE CASCADE ON UPDATE RESTRICT,
	CONSTRAINT numero_contiene_fk FOREIGN KEY (numero) REFERENCES VENTA (numero) ON DELETE CASCADE ON UPDATE RESTRICT,
	CONSTRAINT contiene_pk PRIMARY KEY (codBarras, numero)
);

-- Tabla: CATEGORIA
CREATE TABLE CATEGORIA (
    registro VARCHAR(20) NOT NULL,
    codBarras VARCHAR(20) NOT NULL,
	tipoCategoria CHAR(18) NOT NULL,
	marca VARCHAR(20) NULL,
    descripcion TEXT NULL,
    CONSTRAINT categoria_pk PRIMARY KEY (registro),
	CONSTRAINT codBarras_categoria_fk FOREIGN KEY (codBarras) REFERENCES PRODUCTO (codBarras) ON DELETE CASCADE ON UPDATE RESTRICT
);