#clientes
insert into CLIENTE values('tzk1sca9r@gmail.com','ORGO540830-ggg',SQ_numClie,'higeros',29803,'heroes z','edomex','toluca','oscar','ortiz','garcia');
insert into CLIENTE values('hcyvwv3l2@gmail.com','LORZ570402-zzz',SQ_numClie,'norte',11223,'ortiz G.','colima','colima','zusana','lopez','rivera');
insert into CLIENTE values('5uxpsgbyg@hotmail.com','HEMM680924-zzz',SQ_numClie,'economia',85457,'copilco universidad','cdmx','coyoacan','margarita','hernandez','morales');
insert into CLIENTE values('mw5ksq8c7@gmail.com','GORA840623-zzz',SQ_numClie,'palomas',86515,'copilco universidad','cdmx','coyoacan','arturo','gonzalez','rivera');
insert into CLIENTE values('dor26ky11@gmail.com','HEPE980715-zzz',SQ_numClie,'leones',58478,'aires del sur','chihuahua','chihuahua','edgar','hernandez','perez');
insert into CLIENTE values('jy1fkwdjs@gmail.com','LOCL890305-zzz',SQ_numClie,'arcoiris',86515,'la palma','cdmx','tlalpan','luis alberto','lopez','castellanos');
insert into CLIENTE values('hmzxdrdtu@gmail.com','SISJ570302-zzz',SQ_numClie,'churubusco',58478,'beltran','morelos','cuernavaca','jose','silva','sanchez');
insert into CLIENTE values('zqxjoii9j@gmail.com','GOOA770908-zzz',SQ_numClie,'corregidora',97801,'san andres de totoltepec','cdmx','tlalpan','ana luisa','gonzalez','ortiz');
insert into CLIENTE values('pt4jyozas@gmail.com','ROOJ680120-zzz',SQ_numClie,'revolucion',97801,'6 de mayo','guerrero','chilpancingo','jonathan','rojas','ortega');
insert into CLIENTE values('6vtn21eqr@gmail.com','CACC920530-zzz',SQ_numClie,'independencia',44556,'valle del sol','veracruz','xalapa','carlos','castillo','castro');
insert into CLIENTE values('ee7uftluc@hotmail.com','MAMX751202-ggg',SQ_numClie,'segovia',29803,'alamos','cdmx','benito juarez','oscar','martinez','mora');
insert into CLIENTE values('ijirk3wnx@gmail.com','LOCA550227-zzz',SQ_numClie,'texcoco',46443,'sanchez','edomex','toluca','andrea','lopez','castro');
insert into CLIENTE values('56j5hg71v@gmail.com','LOTF960606-zzz',SQ_numClie,'orquideas',99255,'tepeyac','edomex','ecatepec','felipe','lopez','torres');
insert into CLIENTE values('oje2wxegl@hotmail.com','GOPF870305-zzz',SQ_numClie,'jamaica',99255,'alamos','chihuahua','delicias','luis felipe','gonzalez','perez');
insert into CLIENTE values('wvj9ihxl5@gmail.com','GAPM890321-zzz',SQ_numClie,'durazno',96492,'americas','chihuahua','ciudad juarez','marco antonio','garcia','perez');
insert into CLIENTE values('1lojdfsqc@gmail.com','SAOA990112-zzz',SQ_numClie,'girasol',19345,'tepeyac','edomex','ecatepec','andres','santos','ortiz');
insert into CLIENTE values('e1esa53j8@gmail.com','GAMA000204-zzz',SQ_numClie,'tamarindo',96492,'arcadas','chihuahua','chihuahua','alberto','garcia','morales');
insert into CLIENTE values('fs8dxhmq1@gmail.com','GASC780428-zzz',SQ_numClie,'aldama',19345,'san juan tetepan','cdmx','xochimilco','carlos manuel','garcia','sanchez');
insert into CLIENTE values('l67gipcqc@gmail.com','MASJ930204-zzz',SQ_numClie,'norte',47209,'6 de mayo','guerrero','acapulco','jesus mario','martinez','sierra');
insert into CLIENTE values('owferdfc4@gmail.com','HERJ760401-zzz',SQ_numClie,'las flores',02151,'la palma','cdmx','tlalpan','juliana','hernandez','rojas');
insert into CLIENTE values('h8uh4l7tv@gmail.com','ORGM740826-ggg',SQ_numClie,'cadiz',76620,'alamos','cdmx','benito juarez','martin','ortiz','garcia');
insert into CLIENTE values('68t1ov69r@gmail.com','LOZA980208-zzz',SQ_numClie,'desierto de los leones',46443,'tetelpan','cdmx','alvaro obregon','andrea','lopez','zamorategui');
insert into CLIENTE values('9fwf36mhk@gmail.com','PECK010101-zzz',SQ_numClie,'poniente',47209,'frontera','guerrero','taxco','karilu','peña','castro');
insert into CLIENTE values('ebmarx7js@gmail.com','SIMK950527-zzz',SQ_numClie,'puesta de sol',68670,'los alamos','edomex','naucalpan','karla','silva','morales');
insert into CLIENTE values('rjem417bg@gmail.com','GUSP980204-zzz',SQ_numClie,'azul cielo',02151,'jacarandas','guerrero','acapulco','paola andrea','gutierrez','silva');
insert into CLIENTE values('pnc33c58n@hotmail.com','ZAVA790219-zzz',SQ_numClie,'jalisco',68670,'valle de cristal','veracruz','poza rica','andres','zamorategui','vargas');
insert into CLIENTE values('f70lfa9da@gmail.com','GRPM830118-zzz',SQ_numClie,'militares',55739,'el paraiso','edomex','toluca','mario alberto','granda','perez');
insert into CLIENTE values('a6tcom0zk@gmail.com','MAPE570802-zzz',SQ_numClie,'policia',76620,'insurgentes','hidalgo','tulancingo','edgar','martinez','perez');
insert into CLIENTE values('6y715lnxo@gmail.com','TOMJ970413-zzz',SQ_numClie,'academia',76620,'insurgentes','hidalgo','pachuca','juan fernando','torres','morales');
insert into CLIENTE values('4w4opj6yj@gmail.com','CANL820321-zzz',SQ_numClie,'macadamia',55739,'lindavista','sonora','hermosillo','luis fernando','castillo','narvaez');
insert into CLIENTE values('7io899gbn@gmail.com','PEGD820717-ggg',SQ_numClie,'sur 140',11223,'16 de septiembre','cdmx','miguel hidalgo','daniel','perez','garcia');
insert into CLIENTE values('s5jp4w7uf@gmail.com','LORR031102-zzz',SQ_numClie,'tiziano',46443,'mixcoac','cdmx','benito juarez','renata','lopez','rivera');
insert into CLIENTE values('4mgc8zaqh@gmail.com','GOPE830818-zzz',SQ_numClie,'nintendo',76620,'el paraiso','edomex','naucalpan','enrique','gomez','perez');
insert into CLIENTE values('b2yxjgfq7@gmail.com','AGOC931020-zzz',SQ_numClie,'montes',78253,'roma','tamaulipas','reynosa','carlos ernesto','aguirre','ortiz');
insert into CLIENTE values('bam7jblgj@gmail.com','AGSG790120-zzz',SQ_numClie,'nubes',78253,'rancho nuevo','tamaulipas','reynosa','gilberto','aguirre','santos');
insert into CLIENTE values('6yyk6kdhb@gmail.com','GODF680102-zzz',SQ_numClie,'manzanillo',74796,'rio de luz','edomex','tepotzotlan','felipe','gomez','diaz');
insert into CLIENTE values('p5ignnk0r@hotmail.com','HEMJ961230-zzz',SQ_numClie,'fresas',43773,'la cima','guerrero','acapulco','jaime','hernandez','morales');
insert into CLIENTE values('s4q4sypoa@hotmail.com','LOSM930618-zzz',SQ_numClie,'chapultepec',74796,'barrancas','chihuahua','ciudad cuauhtemoc','manuel andres','lopez','sanchez');
insert into CLIENTE values('4higufz0q@gmail.com','MAMM790723-zzz',SQ_numClie,'zaragoza',78253,'valle verde','jalisco','guadalajara','monica','martinez','morales');
insert into CLIENTE values('ljr9lma58@hotmail.com','GASR731207-zzz',SQ_numClie,'paseo de cristal',44556,'zapotlan','nuevo leon','monterrey','ruben','garcia','santos');
insert into CLIENTE values('wbfafqwps@gmail.com','SAGD801020-ggg',SQ_numClie,'higeros',11223,'la mora','edomex','toluca','daniel','sanchez','garcia');
insert into CLIENTE values('i1rhd0np9@gmail.com','SASM690109-zzz',SQ_numClie,'norte',11223,'el charco','edomex','ecatepec','maricela','santos','silva');
insert into CLIENTE values('x52s0hh91@gmail.com','ALSG000207-zzz',SQ_numClie,'rafael sierra',43773,'san juan','cdmx','iztapalapa','gloria','alvarez','sanchez');
insert into CLIENTE values('scd4tbh5v@gmail.com','MABV920329-zzz',SQ_numClie,'eje 5',88948,'la cerca','edomex','toluca','vanessa','martinez','balbuena');
insert into CLIENTE values('j9odrt6be@gmail.com','BACP860112-zzz',SQ_numClie,'regina',43245,'marroquin','guerrero','taxco','paula','barrera','castillo');
insert into CLIENTE values('52mvshp2z@gmail.com','CASJ001202-zzz',SQ_numClie,'diadema',05927,'la mora','edomex','ecatepec','juan jose','castillon','sanchez');
insert into CLIENTE values('aypkxr8dn@gmail.com','FUSM590130-zzz',SQ_numClie,'insurgentes',88948,'claudia','chihuahua','chihuahua','maria fernanda','fuentes','santos');
insert into CLIENTE values('fznduo9yl@gmail.com','FLPS950820-zzz',SQ_numClie,'oriente',51229,'postal','guerrero','iguala','sara andrea','flores','perez');
insert into CLIENTE values('0jk95l8ur@hotmail.com','MOHP901023-zzz',SQ_numClie,'el salvador',05927,'allende','sonora','hermosillo','pilar','morales','hernandez');
insert into CLIENTE values('ku32qjik6@gmail.com','PEAP890216-zzz',SQ_numClie,'cuauhtemoc',09259,'coltongo','cdmx','azcapotzalco','patricia','perez','aguilar');

#provedores
insert into PROVEDOR values ('hrmz lopez y asociados s.a. de c.v.',1162581213,'oriente','555','tijuana','juan','lopez','contreraz');
insert into PROVEDOR values ('Hermanos Gómez y Ripoldi S.R.L.',6458793210,'vulevar k','s/n','veracruz','maria','sanchez');

#PRODUCTO
insert into PRODUCTO values ('k12asdf5s','acme',500,null,'minas','caja 12 minas .5',5,'8','socieda mercantil del norte');
insert into PRODUCTO values ('ñ28a9as57','varios',206,'caja musical',null,'cajas musical',50,'10','varios sociedad anonima de capital variable del pacifico');
insert into PRODUCTO values ('ef83voe88','lenovo',32,null,'pc lenovo','computadora de sobremesa',8500,'43','Alfarrico S.A.');
insert into PRODUCTO values ('3s6fE46fa','varios',100,'peluche',null,'animal de peluche',15,'125','varios sociedad anonima de capital variable del pacifico');
