




CREATE DATABASE proyecto_bd;
\c proyecto_bd




CREATE TABLE PROVEDORES (
  ID_PROVEDOR         INTEGER NOT NULL,
  RAZON_SOCIAL        VARCHAR(50) NOT NULL,
  ESTADO              VARCHAR(50) NOT NULL,
  CODIGO_POSTAL       INTEGER NOT NULL,
  COLONIA             VARCHAR(40) NOT NULL,
  CALLE               VARCHAR(40) NOT NULL,
  NUMERO              INTEGER NOT NULL,
  NOMBRE              VARCHAR(40) NOT NULL,
  AP_PATERNO          VARCHAR(40) NOT NULL,
  AP_MATERNO          VARCHAR(40),
  ID_TIENDA           INTEGER,
CONSTRAINT PK_PROVEDORES PRIMARY KEY (ID_PROVEDOR)
);

CREATE TABLE TIENDA (
  NOMBRE              VARCHAR(40) NOT NULL,
  ID_TIENDA           INTEGER NOT NULL,
CONSTRAINT PK_TIENDA PRIMARY KEY (ID_TIENDA)
);

CREATE TABLE PRODUCTO_ALMACEN (
  PRECIO_VENTA        REAL NOT NULL,
  PRECIO_COMPRA       REAL NOT NULL,
  FECHA_COMPRA        DATE NOT NULL,
  CANTIDAD_EJEMPLARES INTEGER NOT NULL,
  ID_TIENDA           INTEGER,
  CODIGO_BARRAS       INTEGER NOT NULL,
CONSTRAINT PK_PRODUCTO_ALMACEN PRIMARY KEY (CODIGO_BARRAS)
);

CREATE TABLE VENTA (
  ID_VENTA            INTEGER NOT NULL,
  NUM_VENTA           VARCHAR(10) NOT NULL,
  TOTAL_VENTA         REAL NOT NULL,
  FECHA_VENTA         DATE NOT NULL,
  ID_TIENDA           INTEGER,
  ID_CLIENTE          INTEGER,
CONSTRAINT PK_VENTA PRIMARY KEY (ID_VENTA)
);

CREATE TABLE CLIENTE (
  ID_CLIENTE          INTEGER NOT NULL,
  RFC                 VARCHAR(13) NOT NULL,
  NOMBRE              VARCHAR(40) NOT NULL,
  AP_PATERNO          VARCHAR(40) NOT NULL,
  AP_MATERNO          VARCHAR(40) NOT NULL,
  CALLE               VARCHAR(40) NOT NULL,
  NUMERO              INTEGER NOT NULL,
  COLONIA             VARCHAR(40) NOT NULL,
  CODIGO_POSTAL       INTEGER NOT NULL,
  ESTADO              VARCHAR(40) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO_VENTA (
  DESCRIPCION         VARCHAR(40) NOT NULL,
  MARCA               VARCHAR(40) NOT NULL,
  CANTIDAD            INTEGER NOT NULL,
  TOTAL_ARTICULO      REAL NOT NULL,
  CODIGO_BARRAS       INTEGER NOT NULL,
  ID_VENTA            INTEGER NOT NULL,
CONSTRAINT PK_PRODUCTO_VENTA PRIMARY KEY (CODIGO_BARRAS,ID_VENTA)
);

CREATE TABLE TELEFONO (
  TELEFONO            INTEGER NOT NULL,
  ID_PROVEDOR         INTEGER NOT NULL,
CONSTRAINT PK_TELEFONO PRIMARY KEY (TELEFONO,ID_PROVEDOR)
);

CREATE TABLE EMAIL (
  EMAIL               VARCHAR(40) NOT NULL,
  ID_CLIENTE          INTEGER NOT NULL,
CONSTRAINT PK_EMAIL PRIMARY KEY (EMAIL,ID_CLIENTE)
);

/*============================================================================*/
/*                               FOREIGN KEYS                                 */
/*============================================================================*/
ALTER TABLE PROVEDORES
    ADD CONSTRAINT FK_REFERENCE_1
        FOREIGN KEY (ID_TIENDA)
            REFERENCES TIENDA (ID_TIENDA) ON DELETE CASCADE ON UPDATE CASCADE
 ;


ALTER TABLE PRODUCTO_ALMACEN
    ADD CONSTRAINT FK_REFERENCE_2
        FOREIGN KEY (ID_TIENDA)
            REFERENCES TIENDA (ID_TIENDA) ON DELETE CASCADE ON UPDATE CASCADE
 ;


ALTER TABLE VENTA
    ADD CONSTRAINT FK_REFERENCE_3
        FOREIGN KEY (ID_TIENDA)
            REFERENCES TIENDA (ID_TIENDA) ON DELETE CASCADE ON UPDATE CASCADE
 ;

ALTER TABLE VENTA
    ADD CONSTRAINT FK_REFERENCE_4
        FOREIGN KEY (ID_CLIENTE)
            REFERENCES CLIENTE (ID_CLIENTE) ON DELETE RESTRICT ON UPDATE CASCADE
 ;


ALTER TABLE PRODUCTO_VENTA
    ADD CONSTRAINT FK_REFERENCE_8
        FOREIGN KEY (ID_VENTA)
            REFERENCES VENTA (ID_VENTA) ON DELETE RESTRICT ON UPDATE CASCADE
 ;

ALTER TABLE PRODUCTO_VENTA
    ADD CONSTRAINT FK_REFERENCE_9
        FOREIGN KEY (CODIGO_BARRAS)
            REFERENCES PRODUCTO_ALMACEN (CODIGO_BARRAS) ON DELETE RESTRICT ON UPDATE CASCADE
 ;


ALTER TABLE TELEFONO
    ADD CONSTRAINT FK_REFERENCE_7
        FOREIGN KEY (ID_PROVEDOR)
            REFERENCES PROVEDORES (ID_PROVEDOR) ON DELETE CASCADE ON UPDATE CASCADE
 ;


ALTER TABLE EMAIL
    ADD CONSTRAINT FK_REFERENCE_10
        FOREIGN KEY (ID_CLIENTE)
            REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE
 ;


CREATE INDEX indice_producto_venta 
ON producto_venta (id_venta);