CREATE ROLE ejemplo WITH
	NOLOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT 2
	VALID UNTIL '2022-03-14T09:00'
	PASSWORD '123456';
CREATE TABLE public.estudiante
(
)
;
ALTER TABLE public.estudiante
	OWNER to postgres;
GRANT SELECT, UPDATE, DELETE ON TABLE public.estudiante TO ejemplo;