CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID   smallint        NOT NULL,
    NOMBRE         varchar(200)    NOT NULL,
    RAZON_SOCIAL   varchar(200)    NOT NULL,
    TELEFONO       numeric(10,0)   NOT NULL,
    ESTADO         varchar(30)     NOT NULL,
    CODIGO_POSTAL  numeric(5,0)    NOT NULL,
    COLONIA        varchar(30)     NOT NULL,
    CALLE          varchar(30)     NOT NULL,
    NUM_DOMICILIO  smallint        NOT NULL,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (PROVEEDOR_ID)
);

CREATE TABLE CLIENTE(
    CLIENTE_ID     smallint         NOT NULL,
    RFC            varchar(13)      NOT NULL,
    NOMBRE         varchar(30)      NOT NULL,
    AP_PATERNO     varchar(30)      NOT NULL,
    AP_MATERNO     varchar(30),
    ESTADO         varchar(30)      NOT NULL,
    CODIGO_POSTAL  numeric(5,0)     NOT NULL,
    COLONIA        varchar(30)      NOT NULL,
    CALLE          varchar(30)      NOT NULL,
    NUM_DOMICILIO  smallint         NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
);

CREATE TABLE CATEGORIA(
    CATEGORIA_ID  smallint       NOT NULL,
    DESCRIPCION   varchar(300)   NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (CATEGORIA_ID)
);

CREATE TABLE CORREO(
    CORREO_ID   smallint       NOT NULL,
    CLIENTE_ID  smallint       NOT NULL,
    EMAIL       varchar(200)   NOT NULL,
    CONSTRAINT CORREO_PK PRIMARY KEY (CORREO_ID),
	CONSTRAINT CORREO_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
	REFERENCES CLIENTE (CLIENTE_ID),
	CONSTRAINT CORREO_CLIENTE_ID_EMAIL_UK UNIQUE (CLIENTE_ID,EMAIL)
);

--ALTER TABLE CORREO ADD CONSTRAINT CORREO_CLIENTE_ID_EMAIL_UK UNIQUE (CLIENTE_ID,EMAIL);

--Falta check para venta_id
CREATE TABLE VENTA(
    VENTA_ID           varchar(8)       NOT NULL,
    FECHA_VENTA        date             NOT NULL,
    PAGO_FINAL         numeric(6,2)     NOT NULL,
    CLIENTE_ID         smallint         NOT NULL,
	CANTIDAD_ARTICULOS smallint         NOT NULL,
    CONSTRAINT VENTA_PK PRIMARY KEY (VENTA_ID),
	CONSTRAINT VENTA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
	REFERENCES CLIENTE (CLIENTE_ID)
);

CREATE TABLE PRODUCTO(
    PRODUCTO_ID       smallint        NOT NULL,
    CODIGO_BARRAS     varchar(15)     NOT NULL,
    NOMBRE            varchar(100)    NOT NULL,
    PRECIO_PROVEEDOR  numeric(6,2)    NOT NULL,--por pieza
    FECHA_COMPRA      date            NOT NULL,
    MARCA             varchar(100)    NOT NULL,
    NUM_EJEMPLARES    integer         NOT NULL,
    PROVEEDOR_ID      smallint        NOT NULL,
    CATEGORIA_ID      smallint        NOT NULL,
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (PRODUCTO_ID),
	CONSTRAINT PRODUCTO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
	REFERENCES PROVEEDOR (PROVEEDOR_ID),
	CONSTRAINT PRODUCTO_CATEGORIA_ID_FK FOREIGN KEY (CATEGORIA_ID)
	REFERENCES CATEGORIA (CATEGORIA_ID)
);

CREATE TABLE ARTICULO(
    ARTICULO_ID  smallint        NOT NULL,
    PRODUCTO_ID  smallint        NOT NULL,
    PRECIO       numeric(6,2)    NOT NULL,
    VENTA_ID     varchar(8)      NOT NULL,
    CONSTRAINT ARTICULO_PK PRIMARY KEY (ARTICULO_ID, PRODUCTO_ID),
	CONSTRAINT ARTICULO_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
	REFERENCES PRODUCTO (PRODUCTO_ID),
	CONSTRAINT ARTICULO_VENTA_ID_FK FOREIGN KEY (VENTA_ID)
	REFERENCES VENTA (VENTA_ID)
);

CREATE SEQUENCE PROVEEDOR_PROVEEDOR_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
	
ALTER TABLE PROVEEDOR ALTER COLUMN PROVEEDOR_ID SET DEFAULT nextval('PROVEEDOR_PROVEEDOR_ID_SEQ'::regclass);

CREATE SEQUENCE CLIENTE_CLIENTE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
	
ALTER TABLE CLIENTE ALTER COLUMN CLIENTE_ID SET DEFAULT nextval('CLIENTE_CLIENTE_ID_SEQ'::regclass);

CREATE SEQUENCE CATEGORIA_CATEGORIA_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
	
ALTER TABLE CATEGORIA ALTER COLUMN CATEGORIA_ID SET DEFAULT nextval('CATEGORIA_CATEGORIA_ID_SEQ'::regclass);

CREATE SEQUENCE CORREO_CORREO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
	
ALTER TABLE CORREO ALTER COLUMN CORREO_ID SET DEFAULT nextval('CORREO_CORREO_ID_SEQ'::regclass);

CREATE SEQUENCE PRODUCTO_PRODUCTO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
	
ALTER TABLE PRODUCTO ALTER COLUMN PRODUCTO_ID SET DEFAULT nextval('PRODUCTO_PRODUCTO_ID_SEQ'::regclass);
