CREATE TABLE Paises (
    PaisID INT GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    CONSTRAINT Paises_PK PRIMARY KEY (PaisID)
);

CREATE TABLE Estados (
    EstadoID INT GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    PaisID INT,
    CONSTRAINT ESTADOS_PK PRIMARY KEY (EstadoID),
    CONSTRAINT ESTADOS_PAISID_FK FOREIGN KEY (PaisID) REFERENCES Paises(PaisID)
);

CREATE TABLE Proveedores (
    ProveedorID INT GENERATED BY DEFAULT AS IDENTITY,
    RazonSocial VARCHAR(100) NOT NULL,
    Domicilio_Calle VARCHAR(100),
    Domicilio_Numero VARCHAR(10),
    Domicilio_Colonia VARCHAR(100),
    Domicilio_CodigoPostal VARCHAR(10),
    Domicilio_EstadoID INT,
    Nombre VARCHAR(100) NOT NULL,
    RFC VARCHAR(50) NOT NULL,
    CONSTRAINT Proveedores_pk PRIMARY KEY (ProveedorID),
    CONSTRAINT proveedores_domicilio_estado_fk FOREIGN KEY (Domicilio_EstadoID) REFERENCES Estados(EstadoID)
);

CREATE TABLE ProveedorTelefonos (
    TelefonoID INT GENERATED BY DEFAULT AS IDENTITY,
    ProveedorID INT,
    NumeroTelefono VARCHAR(20),
    TipoTelefono VARCHAR(50), -- Ejemplo: 'Móvil', 'Oficina', 'Fax', etc.
    CONSTRAINT Proveedor_telefonos_pk PRIMARY KEY (TelefonoID),
    CONSTRAINT Proveedortelefono_fk FOREIGN KEY (ProveedorID) REFERENCES Proveedores(ProveedorID)
);

CREATE TABLE Empleados (
    EmpleadoID INT GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    ApellidoPaterno VARCHAR(100) NOT NULL,
    ApellidoMaterno VARCHAR(100),
    FechaNacimiento DATE NOT NULL,
    FechaIngreso DATE NOT NULL,
    CONSTRAINT Empledados_pk PRIMARY KEY (EmpleadoID)
);

CREATE TABLE Clientes (
    ClienteID INT GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    ApellidoPaterno VARCHAR(100) NOT NULL,
    ApellidoMaterno VARCHAR(100),
    Domicilio_Calle VARCHAR(100),
    Domicilio_Numero VARCHAR(10),
    Domicilio_Colonia VARCHAR(100),
    Domicilio_CodigoPostal VARCHAR(10),
    Domicilio_EstadoID INT,
    Email VARCHAR(100),
    RFC VARCHAR(50) NOT NULL,
    CONSTRAINT Clientes_pk PRIMARY KEY (ClienteID),
    CONSTRAINT Clientes_Domicilio FOREIGN KEY (Domicilio_EstadoID) REFERENCES Estados(EstadoID)
);

CREATE TABLE Categorias (
    CategoriaID INT GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion TEXT,
    CONSTRAINT Categorias_pk PRIMARY KEY (CategoriaID)
);

CREATE TABLE Productos (
    ProductoID INT GENERATED BY DEFAULT AS IDENTITY,
    CodigoBarras VARCHAR(50),
    Nombre VARCHAR(100) NOT NULL,
    PrecioCompra DECIMAL(10, 2) NOT NULL,
    PrecioVenta DECIMAL(10, 2) NOT NULL,
    Foto BYTEA,
    Stock NUMERIC NOT NULL,
    CantidadStock INT NOT NULL,
    CategoriaID INT,
    ProveedorID INT,
    CONSTRAINT Productos_pk PRIMARY KEY (ProductoID),
    CONSTRAINT CATEGORIA_FK FOREIGN KEY (CategoriaID) REFERENCES Categorias(CategoriaID),
    CONSTRAINT PROVEEDOR_FK FOREIGN KEY (ProveedorID) REFERENCES Proveedores(ProveedorID)
);

CREATE TABLE Ventas (
    VentaID INT GENERATED BY DEFAULT AS IDENTITY,
    Folio VARCHAR(20) UNIQUE,
    FechaVenta DATE,
    CantidadTotalPagar DECIMAL(10, 2),
    EmpleadoID INT,
    CONSTRAINT VENTAS_PK PRIMARY KEY (VentaID),
    CONSTRAINT VENTAS_EMPLEADO_FK FOREIGN KEY (EmpleadoID) REFERENCES Empleados(EmpleadoID)
);

CREATE TABLE DetalleVenta (
    DetalleVentaID INT GENERATED BY DEFAULT AS IDENTITY,
    VentaID INT,
    ProductoID INT,
    CantidadProducto INT,
    PrecioTotalArticulo DECIMAL(10, 2),
    ClienteID INT,
    CONSTRAINT DETALL_VENTA_PK PRIMARY KEY (DetalleVentaID),
    CONSTRAINT DETALLE_VENTA_VENTAID FOREIGN KEY (VentaID) REFERENCES Ventas(VentaID),
    CONSTRAINT DETALLE_VENTA_PRODUCTO FOREIGN KEY (ProductoID) REFERENCES Productos(ProductoID),
    CONSTRAINT DETALLE_VENTA_CLIENTE FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID)
);


CREATE TABLE ClienteEmails (
    ClienteID INT,
    Email VARCHAR(100) NOT NULL,
    CONSTRAINT CLIENTE_MAILS_PK PRIMARY KEY (ClienteID, Email),
    CONSTRAINT EMAILS_CLIENTES_FK FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID)
);
