
\copy public.administrativo to '/tmp/restaurante_csv/administrativo.csv' with (format csv, header true)
\copy public.categoria to '/tmp/restaurante_csv/categoria.csv' with (format csv, header true)
\copy public.cliente to '/tmp/restaurante_csv/cliente.csv' with (format csv, header true)
\copy public.cocinero to '/tmp/restaurante_csv/cocinero.csv' with (format csv, header true)
\copy public.dependiente to '/tmp/restaurante_csv/dependiente.csv' with (format csv, header true)
\copy public.empleado to '/tmp/restaurante_csv/empleado.csv' with (format csv, header true)
\copy public.estado to '/tmp/restaurante_csv/estado.csv' with (format csv, header true)
\copy public.factura to '/tmp/restaurante_csv/factura.csv' with (format csv, header true)
\copy public.mesero to '/tmp/restaurante_csv/mesero.csv' with (format csv, header true)
\copy public.orden to '/tmp/restaurante_csv/orden.csv' with (format csv, header true)
\copy public.orden_producto to '/tmp/restaurante_csv/orden_producto.csv' with (format csv, header true)
\copy public.producto to '/tmp/restaurante_csv/producto.csv' with (format csv, header true)
\copy public.telefono_empleado to '/tmp/restaurante_csv/telefono_empleado.csv' with (format csv, header true)
