SELECT PRESTAMO.NUM_PRESTAMO, IMPORTE,
NOMBRE_CLIENTE, NOMBRE_SUCURSAL
FROM PRESTAMO JOIN PRESTATARIO
ON PRESTAMO.NUM_PRESTAMO=PRESTATARIO.NUM_PRESTAMO
WHERE NOMBRE_SUCURSAL='COPILCO';

SELECT NOMBRE_CLIENTE, CIUDAD
FROM CLIENTE
WHERE CIUDAD='GUANAJUATO';

SELECT NOMBRE_CLIENTE
FROM PRESTATARIO
UNION
SELECT NOMBRE_CLIENTE
FROM CTA_CLIENTE;

SELECT NOMBRE_CLIENTE
FROM CTA_CLIENTE
EXCEPT (
SELECT NOMBRE_CLIENTE FROM CLIENTE
EXCEPT
SELECT NOMBRE_CLIENTE FROM PRESTATARIO);

SELECT NOMBRE_CLIENTE, IMPORTE
FROM PRESTATARIO JOIN PRESTAMO
ON PRESTAMO.NUM_PRESTAMO=PRESTATARIO.NUM_PRESTAMO
WHERE IMPORTE>5000;




