<?php
echo 'Papeleria Gaston.';
/*
--Aber si ahorra--

*/

/*
Realizado por David Reyes Avila y Daniel Salinas Romero

UNAM-FI-2021
BASE DE DATOS: GRUPO 1 
PROG: ING. FERNANDO ARREOLA FRANCO

ESTE PROYECTAZO FUE PATROSINADO POR EL FABIAN, MIS JEFES, DON GASTON BILLETES, LAS EMPANADAS DEL ANEXO, EL TACO DE WUEVITO DE LA GÜERA
Y LOS PODEROSISIMOS CHILAQUILES DE DON RATA
*/
?>